# Generated by Django 2.0.7 on 2018-08-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ManyToManyField(related_name='person_addresses', to='contact_box.Person'),
        ),
    ]
